### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'metadata' can't have a default value

### ISSUE THREAD

**Issue by admonkey** [kenarkose/Files#1]
I can't migrate after running the default `php artisan files:migration`

Full error:

```

[Illuminate\Database\QueryException]                                                                                                         
  SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'metadata' can't have a default value (SQL: create table `media` (  
  `id` int unsigned not null auto_increment primary key, `path` varchar(255) not null, `name` varchar(255) not null, `extension` varchar(255)  
   not null, `mimetype` varchar(255) not null, `size` bigint unsigned not null, `metadata` text not null default '{}', `type` varchar(255) nu  
  ll, `directory_id` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate utf8_uni  
  code_ci)

```

```
[PDOException]                                                                                                  
  SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'metadata' can't have a default value
```

Using MySQL Ver 14.14 Distrib 5.5.50, for debian-linux-gnu (x86_64) using readline 6.3

**Comment by Hyleeh** [comment]
Hi!
Fixed that error, please re-try and let me know if there are any further problems

**Comment by admonkey** [comment]
thanks! is there any more documentation for this project other than the root `README.md` ?

**Comment by Hyleeh** [comment]
Unfortunately, I am spending most of my time to develop [Nuclear](https://github.com/NuclearCMS/Nuclear) so I really don't have the time write proper documentations at the moment (for any of my packages).

But contributions are much appreciated (Hint: almost all of the API is tested so tests are the best place to look at)
Feel free to add a contributing.md as well:)

By the way, you should check my [Documents](https://github.com/NuclearCMS/documents) package which is built upon this one. It has extended functionality with uploading and downloading.
